### ISSUE TITLE
Maven Test Errors

### ISSUE THREAD

**Issue by kbridgford** [Kibo/AstroAPI#1]
Errors when running mvn clean package. I've been trying to build this for a few days but I'm at a loss.

Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_232, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/jdk8u232-b09/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-54-generic", arch: "amd64", family: "unix"

```
[INFO] ----------------------< cz.kibo.api:astrologyAPI >----------------------
[INFO] Building astrology 1.2.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ astrologyAPI ---
[INFO] Deleting /home/kaze/code/AstroAPI/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ astrologyAPI ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.2:compile (default-compile) @ astrologyAPI ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 59 source files to /home/kaze/code/AstroAPI/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ astrologyAPI ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/kaze/code/AstroAPI/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.2:testCompile (default-testCompile) @ astrologyAPI ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to /home/kaze/code/AstroAPI/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ astrologyAPI ---
[INFO] Surefire report directory: /home/kaze/code/AstroAPI/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@7e0b37bc
Test method executing on thread with id: 14
Test method executing on thread with id: 11
Test method executing on thread with id: 12
Test method executing on thread with id: 17
Test method executing on thread with id: 15
Test method executing on thread with id: 13
Test method executing on thread with id: 16
Test method executing on thread with id: 9
Test method executing on thread with id: 10
Test method executing on thread with id: 8
null
swisseph.SwissephException: File is damaged: byte ordering info not correct.
null
null
swisseph.SwissephException
null
swisseph.SwissephException
null
java.lang.NullPointerException
Test method executing on thread with id: 10
Test method executing on thread with id: 12
Test method executing on thread with id: 16
Test method executing on thread with id: 9
null
Filepointer position 4150869 exceeds file length by 3666815 byte(s).
Test method executing on thread with id: 11
Test method executing on thread with id: 17
Test method executing on thread with id: 10
Test method executing on thread with id: 13
nullTest method executing on thread with id: 14
Test method executing on thread with id: 14
Test method executing on thread with id: 16
Test method executing on thread with id: 8
Test method executing on thread with id: 17

Filepointer position 2147483645 exceeds file length by 2146999591 byte(s).
Test method executing on thread with id: 13
Test method executing on thread with id: 9
Test method executing on thread with id: 15
Test method executing on thread with id: 12
Test method executing on thread with id: 10
null
Filepointer position 2147483645 exceeds file length by 2146999591 byte(s).
Test method executing on thread with id: 15
Test method executing on thread with id: 9
Test method executing on thread with id: 17
null
swisseph.SwissephException
Test method executing on thread with id: 16
Test method executing on thread with id: 9
Test method executing on thread with id: 8
Test method executing on thread with id: 12
Test method executing on thread with id: 10
Test method executing on thread with id: 12
Test method executing on thread with id: 10
Test method executing on thread with id: 11
Test method executing on thread with id: 11
Test method executing on thread with id: 8
null
swisseph.SwissephException
Test method executing on thread with id: 8
null
swisseph.SwissephException
Test method executing on thread with id: 13
Test method executing on thread with id: 15
Test method executing on thread with id: 17
null
java.lang.NullPointerException
Test method executing on thread with id: 16
Test method executing on thread with id: 14
Test method executing on thread with id: 14
Test method executing on thread with id: 15
Test method executing on thread with id: 15
Test method executing on thread with id: 12
Test method executing on thread with id: 9
Test method executing on thread with id: 11
Test method executing on thread with id: 17
Test method executing on thread with id: 17
Test method executing on thread with id: 12
Test method executing on thread with id: 10
Test method executing on thread with id: 9
Test method executing on thread with id: 11
Test method executing on thread with id: 8
Test method executing on thread with id: 16
Test method executing on thread with id: 16
Test method executing on thread with id: 11
Test method executing on thread with id: 9
Test method executing on thread with id: 15
Test method executing on thread with id: 17
Test method executing on thread with id: 13
Test method executing on thread with id: 12
Test method executing on thread with id: 17
Test method executing on thread with id: 15
Test method executing on thread with id: 14
Test method executing on thread with id: 8
Test method executing on thread with id: 11
Test method executing on thread with id: 10
null
Filepointer position 2147483645 exceeds file length by 2146999591 byte(s).
Test method executing on thread with id: 8
nullTest method executing on thread with id: 9
Test method executing on thread with id: 13
Test method executing on thread with id: 17
Test method executing on thread with id: 16
Test method executing on thread with id: 14

Filepointer position 2147483645 exceeds file length by 2146999591 byte(s).
Test method executing on thread with id: 8
Test method executing on thread with id: 10
Test method executing on thread with id: 9
Test method executing on thread with id: 11
Test method executing on thread with id: 15
Test method executing on thread with id: 17
Test method executing on thread with id: 14
Test method executing on thread with id: 15
null
Filepointer position 2147483645 exceeds file length by 2146999591 byte(s).
Test method executing on thread with id: 13
null
Filepointer position 2147483645 exceeds file length by 2146999591 byte(s).
Test method executing on thread with id: 12
Test method executing on thread with id: 16
Test method executing on thread with id: 10
Test method executing on thread with id: 12
Test method executing on thread with id: 8
Test method executing on thread with id: 11
Test method executing on thread with id: 11
Test method executing on thread with id: 10
Test method executing on thread with id: 14
null
java.lang.StringIndexOutOfBoundsException: String index out of range: 47
null
Filepointer position 2147483945 exceeds file length by 2146999891 byte(s).
Test method executing on thread with id: 17
Test method executing on thread with id: 10
null
Filepointer position 2147483645 exceeds file length by 2146999591 byte(s).
null
Filepointer position 2147483645 exceeds file length by 2146999591 byte(s).
Test method executing on thread with id: 15
Test method executing on thread with id: 9
Test method executing on thread with id: 9
Test method executing on thread with id: 16
Test method executing on thread with id: 16
Test method executing on thread with id: 14
Test method executing on thread with id: 12
Test method executing on thread with id: 8
Test method executing on thread with id: 13
Test method executing on thread with id: 11
Test method executing on thread with id: 15
Test method executing on thread with id: 17
Test method executing on thread with id: 9
Test method executing on thread with id: 14
Test method executing on thread with id: 10
Test method executing on thread with id: 12
Test method executing on thread with id: 12
Test method executing on thread with id: 16
Test method executing on thread with id: 17
Test method executing on thread with id: 8
Test method executing on thread with id: 17
Test method executing on thread with id: 17
Test method executing on thread with id: 16
Test method executing on thread with id: 12
Test method executing on thread with id: 14
Test method executing on thread with id: 9
Test method executing on thread with id: 17
Test method executing on thread with id: 13
Test method executing on thread with id: 15
Test method executing on thread with id: 15
Test method executing on thread with id: 11
Test method executing on thread with id: 13
Test method executing on thread with id: 13
Test method executing on thread with id: 9
Test method executing on thread with id: 9
Test method executing on thread with id: 10
null
Filepointer position 2147483645 exceeds file length by 2146178875 byte(s).
Test method executing on thread with id: 8
Test method executing on thread with id: 8
Test method executing on thread with id: 10
Test method executing on thread with id: 10
Test method executing on thread with id: 10
Test method executing on thread with id: 13
Test method executing on thread with id: 12
Test method executing on thread with id: 15
Test method executing on thread with id: 15
Test method executing on thread with id: 15
Test method executing on thread with id: 14
Test method executing on thread with id: 14
Test method executing on thread with id: 11
Test method executing on thread with id: 11
Test method executing on thread with id: 11
Test method executing on thread with id: 11
Test method executing on thread with id: 12
null
Filepointer position 2147483945 exceeds file length by 2146999891 byte(s).
Test method executing on thread with id: 17
Test method executing on thread with id: 12
Test method executing on thread with id: 9
Test method executing on thread with id: 16
Test method executing on thread with id: 8
Test method executing on thread with id: 8
Test method executing on thread with id: 13
Test method executing on thread with id: 8
Test method executing on thread with id: 8
null
swisseph.SwissephException
Test method executing on thread with id: 16
Test method executing on thread with id: 9
Test method executing on thread with id: 9
Test method executing on thread with id: 13
Test method executing on thread with id: 15
null
java.lang.NullPointerException
Test method executing on thread with id: 15
Test method executing on thread with id: 16
null
java.lang.NullPointerException
Tests run: 169, Failures: 19, Errors: 0, Skipped: 0, Time elapsed: 2.438 sec <<< FAILURE!
testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3872)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3894)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3872)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3872)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3872)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.SwissEph.free_planets(SwissEph.java:535)
        at swisseph.SwissEph.swe_close(SwissEph.java:563)
        at swisseph.SwissEph.swe_set_ephe_path(SwissEph.java:633)
        at swisseph.SwissEph.swecalc(SwissEph.java:2873)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.SwissEph.free_planets(SwissEph.java:535)
        at swisseph.SwissEph.swe_close(SwissEph.java:563)
        at swisseph.SwissEph.swe_set_ephe_path(SwissEph.java:633)
        at swisseph.SwissEph.swecalc(SwissEph.java:2873)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3872)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3872)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.021 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3872)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3872)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.065 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.SwissEph.free_planets(SwissEph.java:535)
        at swisseph.SwissEph.swe_close(SwissEph.java:563)
        at swisseph.SwissEph.swe_set_ephe_path(SwissEph.java:633)
        at swisseph.SwissEph.swecalc(SwissEph.java:2873)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.024 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.SwissEph.moshier_moon(SwissEph.java:3446)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3494)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3872)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3872)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.SwissEph.moshier_moon(SwissEph.java:3446)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3494)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3872)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:772)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3894)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SwissEph.swe_set_ephe_path(SwissEph.java:653)
        at swisseph.SwissEph.<init>(SwissEph.java:167)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:36)

testMultiProcessing(swisseph.TestMultithread)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.NullPointerException
        at swisseph.FileData.get_new_segment(FileData.java:778)
        at swisseph.SwissEph.sweph(SwissEph.java:4323)
        at swisseph.SwissEph.sweplan(SwissEph.java:3872)
        at swisseph.SwissEph.sweph_moon(SwissEph.java:3481)
        at swisseph.SwissEph.swecalc(SwissEph.java:2949)
        at swisseph.SwissEph._calc(SwissEph.java:420)
        at swisseph.SwissEph.swe_calc(SwissEph.java:318)
        at swisseph.SweDate.setGlobalTidalAcc(SweDate.java:946)
        at swisseph.SweDate.swi_set_tid_acc(SweDate.java:892)
        at swisseph.SwissEph.swe_calc_ut(SwissEph.java:271)
        at swisseph.TestMultithread.testMultiProcessing(TestMultithread.java:47)


Results :

Failed tests:   testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)
  testMultiProcessing(swisseph.TestMultithread)

Tests run: 169, Failures: 19, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.532 s
[INFO] Finished at: 2019-11-21T12:28:32-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project astrologyAPI: There are test failures.


```

**Comment by Kibo** [comment]
Hi Kazebr

do you have a ephemeris data file in in the right place?

If I can help you contact me at chat (Google Hangout, WhatsApp, Messenger)
Tom

**Comment by kbridgford** [comment]
> 
> 
> Hi Kazebr
> 
> do you have a ephemeris data file in in the right place?
> 
> If I can help you contact me at chat (Google Hangout, WhatsApp, Messenger)
> Tom

Thanks Tom, I will reach out. I really appreciate it.
